### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by pcantalupo** [endrebak/goverlap#2]
Hello,

I just installed goverlap and tried to run the example in the documentation but I get a TypeError. I'm running Miniconda3 Python 3.4.3 on Mac 10.10.5. Am I doing something wrong? Thank you

```
$ goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rat -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt 
# /Users/XXXXX/local/usr/local/miniconda3/bin/goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rat -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt
Getting all genes from biomart for rat (Time: Thu, 19 Nov 2015 18:47:38)
Traceback (most recent call last):
  File "/Users/XXXXX/local/usr/local/miniconda3/bin/goverlap", line 131, in <module>
    main(ontology_to_root, dataset, gene_vectors, genes_experiment, nb_processes, max_genes_prct_limit)
  File "/Users/XXXXX/src/goverlap/go_overlap/main.py", line 84, in main
    all_genes_vector = get_all_genes(dataset, experiment_genes)
  File "/Users/XXXXX/src/goverlap/go_overlap/main.py", line 26, in get_all_genes
    df = get_bm("external_gene_name", "go_id", dataset, "ensembl")
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/biomartian/bm_queries/bm_query.py", line 63, in get_bm
    bm.add_dataset_to_xml(dataset)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py", line 352, in add_dataset_to_xml
    self.attributes(dataset)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py", line 255, in attributes
    if dataset not in [x for k in self.valid_attributes.keys() for x in self.valid_attributes[k]]:
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py", line 423, in _get_valid_attributes
    self.names]
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py", line 380, in _get_names
    ret = self.registry()
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py", line 216, in registry
    ret = self.easyXML(ret)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/services.py", line 184, in easyXML
    return xmltools.easyXML(res)
  File "/Users/XXXXX/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/xmltools.py", line 78, in __init__
    self.data = data[:]
TypeError: 'int' object is not subscriptable
```

**Comment by endrebak** [comment]
Nah, the error is probably mine. Will start checking out this error today.

**Comment by endrebak** [comment]
Getting the same error with biomartian, so am going to fix this by writing my own data getter using mygene.info.

**Comment by endrebak** [comment]
Might also be due to `biomaRt` being down. See http://www.biomart.org/notice.html ?

**Comment by pcantalupo** [comment]
The link you reference http://www.biomart.org/notice.html, says to change the host from 'www.biomart.org' to 'www.ensembl.org'. So, when I do that, it works.

```
library(biomaRt)
listMarts(host="www.ensembl.org")
               biomart               version
1 ENSEMBL_MART_ENSEMBL      Ensembl Genes 82
2     ENSEMBL_MART_SNP  Ensembl Variation 82
3 ENSEMBL_MART_FUNCGEN Ensembl Regulation 82
4    ENSEMBL_MART_VEGA               Vega 62
5                pride        PRIDE (EBI UK)
```

Is it easier to add a `host` option to `goverlap`?

**Comment by endrebak** [comment]
Ah, I did not read that properly.

Yes, I'll look into it.

I should also create an issue to get the underlying library (bioservices)
to print a more helpful report when the server is down. I was really thrown
off by that error message.

**Comment by endrebak** [comment]
Now `biomartian` is updated so that `goverlap` should work again. You need to `pip install biomartian==0.0.19` to get the updated version of biomartian.

Thanks again for raising this issue (and providing the fix).

Ps. goverlap only supports `mouse`, `rat` and `human`, but only because I got lazy in the end and hardcoded a few values. It is easy to support all species in biomart/kegg (should be an overlap of at least 90 IIRC). If you were hoping to use a different species, please file another issue,

Psps. if goverlap stalls when getting genes, just use `cntrl-c`. It usually works on the first attempt, always works on the second
