### ISSUE TITLE
ValueError: provided dataset (rat) is not found

### ISSUE THREAD

**Issue by pcantalupo** [endrebak/goverlap#3]
When I try running the example in the README, I get the below error. Is this due to the switch to ensembl from biomart because of issue #2 ?

```
$ goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rat -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt 
# /Users/xxx/local/usr/local/miniconda3/bin/goverlap -a
# / examples/FeatureCount_ECIIvsDeep.txt -b
# / examples/Simes_Binner_ECIIvsDeep.txt -s rat -v debug -n 30 -o CC,KEGG -l
# / 0.10 -x examples/experiment_genes.txt
Getting all genes from biomart for rat (Time: Wed, 25 Nov 2015 17:49:36)
Traceback (most recent call last):
  File "/Users/xxx/local/usr/local/miniconda3/bin/goverlap", line 131, in
<module>
    main(ontology_to_root, dataset, gene_vectors, genes_experiment,
nb_processes, max_genes_prct_limit)
  File "/Users/xxx/local/lib/goverlap/go_overlap/main.py", line 84, in
main
    all_genes_vector = get_all_genes(dataset, experiment_genes)
  File "/Users/xxx/local/lib/goverlap/go_overlap/main.py", line 26, in
get_all_genes
    df = get_bm("external_gene_name", "go_id", dataset, "ensembl")
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py",
line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py",
line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py",
line 675, in call
    output = self.func(*args, **kwargs)
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/biomartian/bm_queries/bm_query.py",
line 63, in get_bm
    bm.add_dataset_to_xml(dataset)
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py",
line 352, in add_dataset_to_xml
    self.attributes(dataset)
  File
"/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/bioservices/biomart.py",
line 256, in attributes
    raise ValueError("provided dataset (%s) is not found. see
valid_attributes" % dataset)
ValueError: provided dataset (rat) is not found. see valid_attributes
```

**Comment by endrebak** [comment]
Thanks for taking the time to report all these. 

This was a doc-bug.

`goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rnor -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt` should work.

Make sure to `pip install goverlap==0.0.4`.

Any feedback appreciated. Feel free to reopen if not working.

**Comment by pcantalupo** [comment]
I think you forgot to upload 0.0.4 to PyPI. I'm getting the `no matching distribution found` error.

**Comment by endrebak** [comment]
You are correct, now it is uploaded.
