### ISSUE TITLE
NameError: name 'reduce' is not defined

### ISSUE THREAD

**Issue by pcantalupo** [endrebak/goverlap#5]
I installed v0.0.4 by cloning to my local machine and then running `pip install .` from within the `goverlap` directory. Then I tried the example command line again but getting a `NameError`. Maybe my system configuration is messed up? Isn't `reduce` a Python builtin?

```
Getting all genes from biomart for rnor (Time: Thu, 26 Nov 2015 08:31:03)
Make term gene map into bool array for the 473 terms in CC for which associated genes can be found. (Time: Thu, 26 Nov 2015 08:31:04)
Turn term gene bool map into term subtree gene bool map. (Time: Thu, 26 Nov 2015 08:31:04)
# /Users/xxx/local/usr/local/miniconda3/bin/goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rnor -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/xxx/local/lib/goverlap/go_overlap/create_term_subtree_gene_matrix/term_subtree_gene_matrix.py", line 90, in _get_all_genes_in_term_subtree
    subtree_gene_list = reduce(logical_or, gene_vectors)
NameError: name 'reduce' is not defined
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/xxx/local/usr/local/miniconda3/bin/goverlap", line 131, in <module>
    main(ontology_to_root, dataset, gene_vectors, genes_experiment, nb_processes, max_genes_prct_limit)
  File "/Users/xxx/local/lib/goverlap/go_overlap/main.py", line 90, in main
    all_genes_vector, nb_cpus)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/xxx/local/lib/goverlap/go_overlap/create_term_subtree_gene_matrix/term_subtree_gene_matrix.py", line 45, in create_gene_subtree_matrix
    parent_offspring_map, terms_to_genes_bool_df, nb_cpus)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/xxx/local/lib/goverlap/go_overlap/create_term_subtree_gene_matrix/term_subtree_gene_matrix.py", line 110, in get_all_genes_in_term_subtree
    term_subtree_dfs = pool.map(_get_all_genes_in_term_subtree, data_tuples)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
NameError: name 'reduce' is not defined
```

**Comment by endrebak** [comment]
Reduce is a builtin in version 2, but you need to import it specifically in Python 3. Will fix ASAP.

I had remembered it some places, but not everywhere.

(Now I actually remembered to upload to PyPI also. `pip install goverlap==0.0.5`.)
