### ISSUE TITLE
TypeError: can't use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by pcantalupo** [endrebak/goverlap#6]
Sorry to post another error. After upgrading to 0.0.5, I now get this. Thank you for your quick replies.

```
Getting all genes from biomart for rnor (Time: Thu, 26 Nov 2015 10:07:16)
Make term gene map into bool array for the 473 terms in CC for which associated genes can be found. (Time: Thu, 26 Nov 2015 10:07:16)
Turn term gene bool map into term subtree gene bool map. (Time: Thu, 26 Nov 2015 10:07:17)
# /Users/xxx/local/usr/local/miniconda3/bin/goverlap -a examples/FeatureCount_ECIIvsDeep.txt -b examples/Simes_Binner_ECIIvsDeep.txt -s rnor -v debug -n 30 -o CC,KEGG -l 0.10 -x examples/experiment_genes.txt
Traceback (most recent call last):
  File "/Users/xxx/local/usr/local/miniconda3/bin/goverlap", line 131, in <module>
    main(ontology_to_root, dataset, gene_vectors, genes_experiment, nb_processes, max_genes_prct_limit)
  File "/Users/xxx/local/lib/goverlap/go_overlap/main.py", line 90, in main
    all_genes_vector, nb_cpus)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/xxx/local/lib/goverlap/go_overlap/create_term_subtree_gene_matrix/term_subtree_gene_matrix.py", line 28, in create_gene_subtree_matrix
    parent_offspring_map = create_parent_offspring_map(ontology, dataset)
  File "/Users/xxx/local/lib/goverlap/go_overlap/go_hierarchy/compute_parent_offspring_maps.py", line 31, in create_parent_offspring_map
    return create_parent_offspring_map_kegg(dataset)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/xxx/local/lib/goverlap/go_overlap/go_hierarchy/compute_parent_offspring_maps.py", line 48, in create_parent_offspring_map_kegg
    kegg_df = get_pathway_to_definition_map(kegg_id)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/site-packages/kegg/lib.py", line 48, in get_pathway_to_definition_map
    kegg_info = re.sub(clean_kegg_path, "", kegg_path_line)
  File "/Users/xxx/local/usr/local/miniconda3/lib/python3.4/re.py", line 179, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by endrebak** [comment]
The problem is related to the fact that in Python 3 - you have two types of string data, `string` and `bytes`. I'm not handling this correctly - I've only used goverlap with Python 2.7. I really want to support Python 3 so I'm starting to look into it.

I feel bad about the software not working for you, but I'm assuming you are the first to try it with 3+. You reporting bugs is basically you doing free work for me, so I'm the one who should feel bad.

**Comment by endrebak** [comment]
I fixed it in kg. 

```
running upload
Submitting dist/kg-0.0.9.tar.gz to https://pypi.python.org/pypi
Server response (200): OK
```

so if you try `pip install kg==0.0.19` goverlap should work for Python 3 (it does on my machine at least).
